# The title is the title of your Add-On
title: DocMapper
# The description will be shown above the form when activating the Add-On
description: Extractin addresses isn't cool. You know what's cool? Putting those addresses on a map.
# Top level type should always be object
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the current search query
  - query
  # By the currently selected documents
  - selected
# Properties are the fields for your form
